### ISSUE TITLE
Identifying modification of database

### ISSUE THREAD

**Issue by Andrew-Saul** [DataScienceScotland/opendatascot#108]
Is there a way to determine when the database of interest eg. "Ante-Natal Smoking" was last modified within opendatascot?  Is there a way to download a dataset that was modified on a certain day using the package?

**Comment by GordonBryden** [comment]
Not at present but I plan on adding a "get metadata" function to collect that and other data about a dataset.

**Comment by GordonBryden** [comment]
OK, so apparently I created ods_metadata in 2021, and forgot about it.

Your use case would be ods_metadata("smoking-at-booking") and then look at the value "modified" which will give you the time down to the nearest millisecond.

To find all datasets modified on a certain day, you would need to get the list of all datasets using ods_datasets(), apply ods_metadata() to the dataframe (using apply or purrr), and the filter the results.
