### ISSUE TITLE
Missing areas using get_spatial_layer

### ISSUE THREAD

**Issue by AlexStead** [DataScienceScotland/opendatascot#112]
Hi,

I'm having an issue using the `get_spatial_layer` function to download data on the boundaries of census geographies. The function appears to work fine when I use it to download population-weighted centroids, but when I download boundary data on data zones or intermediate zones there are 1,000 or 500 missing, respectively. Here are the commands I am using:

```
DZ11 <- get_spatial_layer("https://maps.gov.scot/server/rest/services/ScotGov/StatisticalUnits/MapServer/2")
IZ11 <- get_spatial_layer("https://maps.gov.scot/server/rest/services/ScotGov/StatisticalUnits/MapServer/6")
```

If I then ggplot these data, we can see the missing DZs and IZs quite clearly - see the attached jpg files.

![DZ_boundaries](https://github.com/DataScienceScotland/opendatascot/assets/101743228/113ea11a-7035-4b59-96f1-74efafe43de8)
![IZ_boundaries](https://github.com/DataScienceScotland/opendatascot/assets/101743228/84f79c79-03d8-4572-a437-a2b81290399e)

**Comment by GordonBryden** [comment]
Hi Alex, I'm afraid get_spatial_layer is not from this library, and I don't have any control over the API or databases you are pulling them from. You will need to contact those teams instead.

**Comment by AlexStead** [comment]
Oops, my mistake! For some reason I was sure it was from the opendatascot package!
