### ISSUE TITLE
Return units and geographical code

### ISSUE THREAD

**Issue by jsphdms** [DataScienceScotland/opendatascot#17]
Currently scotgov_get() only returns geographical label

**Comment by jsphdms** [comment]
Before closing, is it worth keeping geographical labels too? I can imagine those being useful

**Comment by GordonBryden** [comment]
I've managed to crack this with some delving into SPARQL's string manipulation. My solution relies on every ODS dataset having a geography component (even if it's just one for "Scotland"). So far this looks like a valid assumption, but I'll open up a new issue to impliment a more generalisable solution.

**Comment by GordonBryden** [comment]
Also, I can't edit github for some reason (probably do to SCOTS). I'll try making my edit at home later.
