### ISSUE TITLE
Minimise CI build time

### ISSUE THREAD

**Issue by jsphdms** [DataScienceScotland/opendatascot#36]
Tips: https://ropensci.github.io/dev_guide/ci.html

**Comment by GordonBryden** [comment]
I've brought the time down from ~10 minutes to below 3. Our main problem was that the examples in the roxygen rode were being run during build time, causing long running calls to statistics.gov.scot. I've just removed these for now.

The testthat calls were also causing slow builds. These now do fake calls thanks to httptest, which speeds us up, and makes us much less vulnerable to statistics.gov.scot being down
