### ISSUE TITLE
ods_find_lower_geographies uses refArea code, but ods_dataset function uses refArea label

### ISSUE THREAD

**Issue by GregorBoyd** [DataScienceScotland/opendatascot#83]
Hi - just having a first play around with this. Really impressive stuff. 

I tried out the Geography manipulation example from the Read Me and it worked perfectly. I then tried it with a 2011 Intermediate Zone (S02002003), but it returned nothing. From a bit of digging it looks like the issue is that the ods_find_lower_geographies uses refArea code, but ods_dataset function uses refArea label.

The reason this is an issue is that the 2001 Data Zones weren't named so their labels are set as S-codes, but for 2011 Data Zones the labels are their names.

Hope this helps. Give me a call if anything is unclear. Sorry if this has already been logged - I had a look but couldn't see it although might be related to #79.

**Comment by GordonBryden** [comment]
Thanks for finding that - I'll see if I can implement a fix

**Comment by GordonBryden** [comment]
refArea now no longer uses labels at all. Originally a measure to speed up queries, it has the side effect of solving this issue.
