### ISSUE TITLE
Make it clearer how to reduce larger data sets on ods_structure that fail on time out

### ISSUE THREAD

**Issue by Koesters** [DataScienceScotland/opendatascot#97]
```
ods_structure(dataset = "population-estimates-current-geographic-boundaries")
Error in ods_query_database(endpoint, query) : 
  Request has timed out, suggesting the data is too large for statistics.gov.scot to return. Either add more filters to ods_dataset(), or use get_csv().
       Check ods_structure for categories to filter on.
```
_**ods_structure**_ fails with advice to use _**ods_structure**_ again 

additionally advice _**get_csv()**_ should be **_ods_get_csv()_**

`ods_structure(dataset = "social-work-reports")`

**Comment by GordonBryden** [comment]
I suspect this is caused by the data set have a very large number of observations, which shouldn't affect ods_structure but since it is there might be a mistake in the way it's making the SPARQL queries to get the dimensions.

**Comment by capncodewash** [comment]
I have the same issue with getting the structure for the mid-year population estimates dataset:

`> opendatascot::ods_structure('population-estimates-current-geographic-boundaries')
Error in ods_query_database(endpoint, query) : 
  Request has timed out, suggesting the data is too large for statistics.gov.scot to return. Either add more filters to ods_dataset(), or use get_csv().
       Check ods_structure for categories to filter on.`

It's not clear what I can do to reduce the data volume: adding filters to ods_dataset doesn't seem to work:

`> opendatascot::ods_dataset('population-estimates-current-geographic-boundaries', refPeriod = "2019", geography = "la")
Error in ods_query_database(endpoint, query) : 
  Request has timed out, suggesting the data is too large for statistics.gov.scot to return. Either add more filters to ods_dataset(), or use get_csv().
       Check ods_structure for categories to filter on.`

Thanks for any assistance!

**Comment by GordonBryden** [comment]
This seems to be to do with the sheer size and dimensionality of this dataset. I'll need to re-write ods_structure to handle this.

**Comment by GordonBryden** [comment]
ods_structure re-written using the advice from swirrl. All ods_structures on valid datasets will now work.
